# LOGISTIC REGRESSION

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split  
from sklearn.preprocessing import StandardScaler   
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report  

In [9]:
data_set=pd.read_csv(r"C:\Users\santh\OneDrive\Desktop\studies\machine learning\mlproject\healthcare-dataset-stroke-data.csv")

In [10]:
data_set

id  gender   age  hypertension  heart_disease ever_married  \
0      9046    Male  67.0             0              1          Yes   
1     51676  Female  61.0             0              0          Yes   
2     31112    Male  80.0             0              1          Yes   
3     60182  Female  49.0             0              0          Yes   
4      1665  Female  79.0             1              0          Yes   
...     ...     ...   ...           ...            ...          ...   
5105  18234  Female  80.0             1              0          Yes   
5106  44873  Female  81.0             0              0          Yes   
5107  19723  Female  35.0             0              0          Yes   
5108  37544    Male  51.0             0              0          Yes   
5109  44679  Female  44.0             0              0          Yes   

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0           Private          Urban             228.69  36.6  formerly smoked   
1     Self-employed          Rural             202.21   NaN     never smoked   
2           Private          Rural             105.92  32.5     never smoked   
3           Private          Urban             171.23  34.4           smokes   
4     Self-employed          Rural             174.12  24.0     never smoked   
...             ...            ...                ...   ...              ...   
5105        Private          Urban              83.75   NaN     never smoked   
5106  Self-employed          Urban             125.20  40.0     never smoked   
5107  Self-employed          Rural              82.99  30.6     never smoked   
5108        Private          Rural             166.29  25.6  formerly smoked   
5109       Govt_job          Urban              85.28  26.2          Unknown   

      stroke  
0          1  
1          1  
2          1  
3          1  
4          1  
...      ...  
5105       0  
5106       0  
5107       0  
5108       0  
5109       0  

[5110 rows x 12 columns]

In [11]:
cols = ['gender','ever_married','work_type','Residence_type','smoking_status']

In [12]:
data_set[cols] = data_set[cols].apply(LabelEncoder().fit_transform)

In [13]:
a=data_set.dropna(subset = ['bmi'])

In [14]:
a

id  gender   age  hypertension  heart_disease  ever_married  \
0      9046       1  67.0             0              1             1   
2     31112       1  80.0             0              1             1   
3     60182       0  49.0             0              0             1   
4      1665       0  79.0             1              0             1   
5     56669       1  81.0             0              0             1   
...     ...     ...   ...           ...            ...           ...   
5104  14180       0  13.0             0              0             0   
5106  44873       0  81.0             0              0             1   
5107  19723       0  35.0             0              0             1   
5108  37544       1  51.0             0              0             1   
5109  44679       0  44.0             0              0             1   

      work_type  Residence_type  avg_glucose_level   bmi  smoking_status  \
0             2               1             228.69  36.6               1   
2             2               0             105.92  32.5               2   
3             2               1             171.23  34.4               3   
4             3               0             174.12  24.0               2   
5             2               1             186.21  29.0               1   
...         ...             ...                ...   ...             ...   
5104          4               0             103.08  18.6               0   
5106          3               1             125.20  40.0               2   
5107          3               0              82.99  30.6               2   
5108          2               0             166.29  25.6               1   
5109          0               1              85.28  26.2               0   

      stroke  
0          1  
2          1  
3          1  
4          1  
5          1  
...      ...  
5104       0  
5106       0  
5107       0  
5108       0  
5109       0  

[4909 rows x 12 columns]

In [15]:
x=a.iloc[:,1:11].values
y=a.iloc[:,11].values

In [16]:
print(x)
print(y)

[[  1.    67.     0.   ... 228.69  36.6    1.  ]
 [  1.    80.     0.   ... 105.92  32.5    2.  ]
 [  0.    49.     0.   ... 171.23  34.4    3.  ]
 ...
 [  0.    35.     0.   ...  82.99  30.6    2.  ]
 [  1.    51.     0.   ... 166.29  25.6    1.  ]
 [  0.    44.     0.   ...  85.28  26.2    0.  ]]
[1 1 1 ... 0 0 0]


In [17]:
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0)

In [18]:
st_x= StandardScaler()    
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test)  

In [19]:
classifier= LogisticRegression(random_state=0)  
classifier.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [20]:
y_pred=classifier.predict(x_test)

In [21]:
cm= confusion_matrix(y_test,y_pred)  

In [22]:
print(cm)

[[1179    0]
 [  49    0]]


In [23]:
print('accuracy score is ',accuracy_score(y_test,y_pred)*100)

accuracy score is  96.00977198697068


In [24]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98      1179
           1       0.00      0.00      0.00        49

    accuracy                           0.96      1228
   macro avg       0.48      0.50      0.49      1228
weighted avg       0.92      0.96      0.94      1228



C:\Users\santh\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\santh\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\santh\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# NAIVE BAYES CLASSIFIER

In [25]:
from sklearn.naive_bayes import GaussianNB

In [26]:
classifier = GaussianNB()

In [27]:
classifier.fit(x_train,y_train)

GaussianNB()

In [28]:
y_pre=classifier.predict(x_test)

In [29]:
confusionmatrix=confusion_matrix(y_test,y_pre)

In [30]:
print(confusionmatrix)

[[1044  135]
 [  24   25]]


In [31]:
print('accuracy score',accuracy_score(y_test,y_pre)*100)

accuracy score 87.05211726384366


In [32]:
print(classification_report(y_test,y_pre))

              precision    recall  f1-score   support

           0       0.98      0.89      0.93      1179
           1       0.16      0.51      0.24        49

    accuracy                           0.87      1228
   macro avg       0.57      0.70      0.58      1228
weighted avg       0.94      0.87      0.90      1228



# K-NEAREST NEIGHBOR (KNN)

In [33]:
from sklearn.neighbors import KNeighborsClassifier

In [34]:
classifier=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [36]:
y_prediction=classifier.predict(x_test)

In [38]:
#print(y_prediction)

In [39]:
conmax=confusion_matrix(y_test,y_prediction)

In [41]:
print(conmax)

[[1175    4]
 [  49    0]]


In [44]:
print('the accuracy score',accuracy_score(y_test,y_prediction)*100)

the accuracy score 95.68403908794788


In [45]:
print('the classification report',classification_report(y_test,y_prediction))

the classification report               precision    recall  f1-score   support

           0       0.96      1.00      0.98      1179
           1       0.00      0.00      0.00        49

    accuracy                           0.96      1228
   macro avg       0.48      0.50      0.49      1228
weighted avg       0.92      0.96      0.94      1228

